spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/todo_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
app:
  cors:
    origins:
      - http://localhost:4200
      - https://todo-app-frontend-dev.herokuapp.com